doctrine:
  orm:
    mappings:
      addresses_address:
        type: annotation
        is_bundle: false
        dir: "%kernel.root_dir%/../src/Backend/Modules/Addresses/Domain/Address"
        alias: AddressesAddress
        prefix: Backend\Modules\Addresses\Domain\Address
      addresses_group:
        type: annotation
        is_bundle: false
        dir: "%kernel.root_dir%/../src/Backend/Modules/Addresses/Domain/Group"
        alias: AddressesGroup
        prefix: Backend\Modules\Addresses\Domain\Group