doctrine:
  dbal:
    types:
      addresses_group_image: Backend\Modules\Addresses\Domain\Group\GroupImageType
      addresses_address_image: Backend\Modules\Addresses\Domain\Address\AddressImageType
      addresses_address_logo: Backend\Modules\Addresses\Domain\Address\AddressLogoType
      addresses_address_background: Backend\Modules\Addresses\Domain\Address\AddressBackgroundType
  orm:
    mappings:
      addresses_address:
        type: annotation
        is_bundle: false
        dir: "%kernel.root_dir%/../src/Backend/Modules/Addresses/Domain/Address"
        alias: AddressesAddress
        prefix: Backend\Modules\Addresses\Domain\Address
      addresses_group:
        type: annotation
        is_bundle: false
        dir: "%kernel.root_dir%/../src/Backend/Modules/Addresses/Domain/Group"
        alias: AddressesGroup
        prefix: Backend\Modules\Addresses\Domain\Group